version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.190.2-alpine
    networks:
      - jenkins
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins:/var/jenkins_home
  selenium-chrome:
    image: selenium/standalone-chrome:3.141.59
    shm_size: "2gb"
    networks:
      - jenkins
    ports:
      - "4444:4444"

networks:
  jenkins:
